### ISSUE TITLE
mod not working after patch

### ISSUE THREAD

**Issue by Mephistou** [TeraProxy/Inspector#7]
Error: [dispatch] [inspector] hook: Error: obsolete definition (S_USER_PAPERDOLL_INFO.10)
    at Dispatch.createHook (E:\3D Objects\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:247:27)
    at Dispatch.hook (E:\3D Objects\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (E:\3D Objects\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at new PlayerInspector (E:\3D Objects\CaaliTeraProxy\mods\Inspector\index.js:25:9)
    at ModuleManager.load (E:\3D Objects\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at E:\3D Objects\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (E:\3D Objects\CaaliTeraProxy\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (E:\3D Objects\CaaliTeraProxy\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by TeraProxy** [comment]
A definition needs to be updated. I have no access to a PC right now but I'll try to update the mods as quickly as possible.

**Comment by TeraProxy** [comment]
Hi @Mephistou ,
should be fixed now.
